import { ArrowRight, BookOpen, FileText, GraduationCap, MapPin, MonitorUp, Search, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { assets } from "../data/assets";
import "./InformationPages.css";
const news=[
 {slug:"huong-dan-nop-ho-so-truc-tuyen",image:assets.newsOnlineApplication,tag:"Thông báo",title:"Hướng dẫn nộp hồ sơ trực tuyến",text:"Các bước chuẩn bị và gửi hồ sơ trên hệ thống."},
 {slug:"hoat-dong-boi-duong-nghiep-vu-cong-doan",image:assets.trainingClassroom,tag:"Hoạt động",title:"Hoạt động bồi dưỡng nghiệp vụ công đoàn",text:"Thông tin về hoạt động đào tạo và bồi dưỡng."},
 {slug:"cap-nhat-noi-dung-chuyen-mon-giao-duc",image:assets.newsEducationContent,tag:"Chuyên môn",title:"Cập nhật nội dung chuyên môn giáo dục",text:"Tổng hợp nội dung phục vụ công tác chuyên môn."},
];
function Crumbs({detail=false}:{detail?:boolean}){return <p className="info-crumb">Trang chủ <span>/</span> <Link to={detail?"/tin-tuc":"/gioi-thieu"}>{detail?"Tin tức":"Giới thiệu"}</Link>{detail&&<><span>/</span><b>Thông báo tuyển sinh</b></>}</p>}
export function AboutPage(){return <><section className="about-top"><div className="container about-top__grid"><div><Crumbs/><p className="info-kicker">VỀ NHÀ TRƯỜNG</p><h1>Đào tạo và bồi dưỡng vì sự<br/>phát triển của đội ngũ giáo dục</h1><p>Trường là đơn vị sự nghiệp trực thuộc<br/>Công đoàn Giáo dục Việt Nam.</p></div><div className="about-top__photo"><img src={assets.heroEducators} alt="Đội ngũ cán bộ giáo dục"/></div></div></section><section className="about-body"><div className="container"><div className="about-cards"><article><i><GraduationCap/></i><div><h2>Chức năng</h2><p>Đào tạo, bồi dưỡng đội ngũ cán bộ, công chức, viên chức trong hệ thống công đoàn và ngành giáo dục; bồi dưỡng chuyên môn, nghiệp vụ sư phạm và quản lý giáo dục.</p></div></article><article><i><Users/></i><div><h2>Đối tượng bồi dưỡng</h2><p>Cán bộ công đoàn ngành địa phương, cán bộ công đoàn các cấp, giáo viên và cán bộ quản lý giáo dục.</p></div></article></div><article className="unit-card"><h2>Thông tin đơn vị</h2><div><span><FileText/>Mã số thuế: 0301453684</span><span><MapPin/>205 Võ Thị Sáu, Phường Xuân Hoà,<br/>Thành phố Hồ Chí Minh, Việt Nam</span><Link to="/chuong-trinh">Xem chương trình đào tạo <ArrowRight/></Link></div></article></div></section></>}
export function NewsPage(){return <><section className="news-hero"><div className="container"><p className="info-crumb">Trang chủ <span>/</span> <b>Tin tức</b></p><div className="news-hero__copy"><p className="info-kicker">TIN TỨC & THÔNG BÁO</p><h1>Cập nhật thông tin từ nhà trường</h1><p>Theo dõi thông báo tuyển sinh, hoạt động bồi dưỡng<br/>và thông tin chuyên môn.</p></div><article className="featured-strip"><div><small>Thông báo</small><h2>Thông tin tuyển sinh các chương trình bồi dưỡng</h2><p>Cập nhật nội dung và hướng dẫn đăng ký chương trình<br/>dành cho cán bộ, giáo viên và cán bộ quản lý giáo dục.</p></div><img src={assets.newsFeatureEnrollment} alt="Tư vấn chương trình bồi dưỡng"/></article></div></section><section className="news-list"><div className="container"><div className="news-tools"><label><Search/><input placeholder="Tìm kiếm tin tức"/></label><div><button className="active">Tất cả</button><button>Thông báo</button><button>Hoạt động</button><button>Chuyên môn</button></div></div><div className="news-cards">{news.map(item=><article key={item.slug}><img src={item.image} alt=""/><div><small>{item.tag}</small><h2>{item.title}</h2><p>{item.text}</p><Link to={`/tin-tuc/${item.slug}`}>Xem chi tiết <ArrowRight/></Link></div></article>)}</div><div className="news-pages"><button className="active">01</button><button>02</button><button>Tiếp theo <ArrowRight/></button></div></div></section></>}
export function NewsDetailPage(){return <><section className="detail-head"><div className="container"><Crumbs detail/><p className="info-kicker">Thông báo</p><h1>Thông tin tuyển sinh các chương trình bồi dưỡng</h1><p>Cập nhật nội dung và hướng dẫn đăng ký chương trình dành cho cán bộ, giáo viên<br/>và cán bộ quản lý giáo dục.</p></div></section><section className="detail-content"><div className="container detail-grid"><main><img src={assets.trainingClassroom} alt="Lớp bồi dưỡng"/><h2>Các lĩnh vực bồi dưỡng</h2><p>Nhà trường tổ chức các chương trình tập trung vào nghiệp vụ công đoàn, nghiệp vụ sư phạm<br/>và quản lý giáo dục.</p><ul><li>Nghiệp vụ công đoàn</li><li>Nghiệp vụ sư phạm</li><li>Quản lý giáo dục</li></ul><h2>Cách đăng ký</h2><p>Người học lựa chọn chương trình, gửi thông tin đăng ký và hoàn thiện hồ sơ trực tuyến<br/>trên hệ thống.</p></main><aside><h2>Tin liên quan</h2>{news.map((item,i)=>{const Icon=[MonitorUp,Users,BookOpen][i];return <Link to={`/tin-tuc/${item.slug}`} key={item.slug}><i><Icon/></i><span>{item.title}</span><ArrowRight/></Link>})}</aside></div><div className="container detail-cta"><span>Quan tâm đến chương trình bồi dưỡng?</span><Link to="/dang-ky">Đăng ký chương trình <ArrowRight/></Link></div></section></>}
